# Portable path configuration (override with environment variables).
project_dir <- Sys.getenv("SHOOT_REGEN_PROJECT_DIR", unset = ".")
output_root <- Sys.getenv("SHOOT_REGEN_OUTPUT_DIR", unset = file.path(project_dir, "02_results"))
external_data_dir <- Sys.getenv("SHOOT_REGEN_EXTERNAL_DATA_DIR", unset = file.path(project_dir, "external_data"))
work_dir <- Sys.getenv("SHOOT_REGEN_WORK_DIR", unset = ".")

suppressPackageStartupMessages({library(Seurat);library(Matrix);library(ggplot2);library(dplyr);library(tidyr);library(scales);library(org.At.tair.db);library(AnnotationDbi)})
indir<-file.path(project_dir, "02_results/01_cell_cycle_related/cell_cycle_ztq")
input_rds<-file.path(project_dir, "01_obj/01_WT_snRNA/03_snRNA_C0-2-3-subclustered_res0.4_SIM4-SIM16.rds")
outdir<-Sys.getenv("ZTQ_CYCLE_OUTDIR",file.path(output_root, "140_WT_C02418_ZTQ_S_vs_merged_G2M_expression"));dir.create(outdir,recursive=TRUE,showWarnings=FALSE)
clusters<-c("0","2","4","1","8");programs<-c("S","G2/M");program_cols<-c("S"="#DE6E56","G2/M"="#6489B9")
read_gene<-function(f){x<-read.delim(f,header=FALSE,stringsAsFactors=FALSE);unique(toupper(trimws(x[[1]])))}
g2<-read_gene(file.path(indir,"cell_cycle_G2_markers_ztq.txt"));m<-read_gene(file.path(indir,"cell_cycle_M_markers_ztq.txt"));s<-read_gene(file.path(indir,"cell_cycle_S_markers_ztq.txt"));g2m<-union(g2,m)
overlap_g2_m<-intersect(g2,m);overlap_s_g2m<-intersect(s,g2m)
sets<-list(S=s,`G2/M`=g2m);long<-bind_rows(lapply(names(sets),function(x)data.frame(program=x,gene_id=sets[[x]])))
write.csv(data.frame(gene_id=g2,source="G2"),file.path(outdir,"00_ZTQ_G2_genes.csv"),row.names=FALSE);write.csv(data.frame(gene_id=m,source="M"),file.path(outdir,"00_ZTQ_M_genes.csv"),row.names=FALSE);write.csv(data.frame(gene_id=g2m,program="G2/M"),file.path(outdir,"01_merged_G2M_genes.csv"),row.names=FALSE);write.csv(long,file.path(outdir,"02_S_and_merged_G2M_gene_sets_long.csv"),row.names=FALSE)
write.csv(data.frame(comparison=c("G2∩M","S∩G2/M"),n_overlap=c(length(overlap_g2_m),length(overlap_s_g2m)),genes=c(paste(overlap_g2_m,collapse=";"),paste(overlap_s_g2m,collapse=";"))),file.path(outdir,"03_gene_set_overlap_QC.csv"),row.names=FALSE)

obj<-readRDS(input_rds);obj$analysis_cluster<-factor(as.character(obj$subcluster),levels=clusters);obj<-subset(obj,subset=!is.na(analysis_cluster));DefaultAssay(obj)<-"RNA";obj<-NormalizeData(obj,verbose=FALSE);expr<-GetAssayData(obj,assay="RNA",slot="data")
long$detected<-long$gene_id%in%rownames(expr);write.csv(long,file.path(outdir,"04_gene_detection_QC.csv"),row.names=FALSE);det<-long[long$detected,,drop=FALSE]
genes<-unique(det$gene_id);gm<-sapply(clusters,function(cl)Matrix::rowMeans(expr[genes,obj$analysis_cluster==cl,drop=FALSE]));rownames(gm)<-genes;colnames(gm)<-clusters;gz<-t(scale(t(gm)));gz[!is.finite(gz)]<-0;gz<-pmax(pmin(gz,2.5),-2.5)
sm<-AnnotationDbi::select(org.At.tair.db,keys=genes,keytype="TAIR",columns="SYMBOL");sm<-sm[!duplicated(sm$TAIR),];symbol<-setNames(sm$SYMBOL,sm$TAIR)
stats<-det;stats$symbol<-unname(symbol[stats$gene_id]);stats$dynamic_range<-apply(gm[stats$gene_id,,drop=FALSE],1,function(x)max(x)-min(x));stats$peak_state<-clusters[max.col(gm[stats$gene_id,,drop=FALSE],ties.method="first")]
for(cl in clusters){stats[[paste0("mean_expression_C",cl)]]<-gm[stats$gene_id,cl];stats[[paste0("Zscore_C",cl)]]<-gz[stats$gene_id,cl]};write.csv(stats,file.path(outdir,"05_gene_mean_expression_and_Zscore.csv"),row.names=FALSE)

curve<-bind_rows(lapply(programs,function(p){g<-det$gene_id[det$program==p];data.frame(program=p,subcluster=clusters,mean_gene_Zscore=colMeans(gz[g,,drop=FALSE]),n_genes=length(g))}));curve$program<-factor(curve$program,levels=programs);curve$subcluster<-factor(curve$subcluster,levels=clusters);write.csv(curve,file.path(outdir,"06_S_and_G2M_module_expression_pattern.csv"),row.names=FALSE)
p<-ggplot(curve,aes(subcluster,mean_gene_Zscore,color=program,group=program))+geom_hline(yintercept=0,lty=2,color="#BDBDBD",linewidth=.35)+geom_line(linewidth=1.15)+geom_point(size=3)+scale_color_manual(values=program_cols)+labs(x="Trajectory state",y="Mean gene-wise Z-score",color=NULL,title="ZTQ S and merged G2/M programs",subtitle="Expression across 0 → 2 → 4 → 1 → 8")+theme_classic(base_family="Arial",base_size=10)+theme(axis.text=element_text(color="#222222",size=9),axis.text.x=element_text(face="bold"),axis.title=element_text(face="bold"),plot.title=element_text(face="bold",size=10.5),plot.subtitle=element_text(size=8.5),legend.position="top",legend.justification="left",plot.margin=margin(4,5,4,4));save2<-function(p,n,w,h){ggsave(file.path(outdir,paste0(n,".pdf")),p,width=w,height=h,device=cairo_pdf,bg="white");ggsave(file.path(outdir,paste0(n,".png")),p,width=w,height=h,dpi=500,bg="white")};save2(p,"07_ZTQ_S_vs_merged_G2M_module_expression_pattern",4.8,3.5)

# Full heatmap, with phase-specific genes ordered by peak state and dynamic range.
orddf<-stats%>%arrange(factor(program,levels=programs),match(peak_state,clusters),desc(dynamic_range));all_order<-orddf$gene_id
al<-as.data.frame(as.table(gz[all_order,clusters,drop=FALSE]),stringsAsFactors=FALSE);colnames(al)<-c("gene_id","subcluster","Zscore");al$subcluster<-factor(al$subcluster,levels=clusters);al$program<-factor(orddf$program[match(al$gene_id,orddf$gene_id)],levels=programs);al$gene<-factor(al$gene_id,levels=rev(all_order))
pall<-ggplot(al,aes(subcluster,gene,fill=Zscore))+geom_raster()+facet_grid(program~.,scales="free_y",space="free_y",switch="y")+scale_fill_gradient2(low="#89A9CE",mid="#F5F5F5",high="#DD776E",limits=c(-2.5,2.5),name="Gene-wise\nZ-score")+labs(x="Trajectory state",y=NULL)+theme_classic(base_family="Arial",base_size=9)+theme(axis.text.x=element_text(face="bold"),axis.text.y=element_blank(),axis.ticks=element_blank(),axis.title.x=element_text(face="bold"),strip.text.y=element_text(face="bold",size=9),strip.background=element_rect(fill="#F0F0F0",color=NA),panel.spacing.y=grid::unit(.8,"mm"),plot.margin=margin(4,5,4,4));save2(pall,"08_all_ZTQ_S_and_G2M_genes_expression_heatmap",4.7,6.4)

# Top 25 dynamic named genes per program.
top<-stats%>%group_by(program)%>%arrange(desc(!is.na(symbol)&symbol!=""),desc(dynamic_range),.by_group=TRUE)%>%slice_head(n=25)%>%ungroup();top<-top%>%arrange(factor(program,levels=programs),match(peak_state,clusters),desc(dynamic_range));top$display_gene<-ifelse(is.na(top$symbol)|top$symbol=="",top$gene_id,top$symbol);top$display_gene<-make.unique(top$display_gene);write.csv(top,file.path(outdir,"09_top25_dynamic_genes_per_program.csv"),row.names=FALSE)
tl<-as.data.frame(as.table(gz[top$gene_id,clusters,drop=FALSE]),stringsAsFactors=FALSE);colnames(tl)<-c("gene_id","subcluster","Zscore");tl$subcluster<-factor(tl$subcluster,levels=clusters);tl$program<-factor(top$program[match(tl$gene_id,top$gene_id)],levels=programs);tl$gene<-factor(top$display_gene[match(tl$gene_id,top$gene_id)],levels=rev(top$display_gene))
pt<-ggplot(tl,aes(subcluster,gene,fill=Zscore))+geom_tile(color="white",linewidth=.3)+facet_grid(program~.,scales="free_y",space="free_y",switch="y")+scale_fill_gradient2(low="#89A9CE",mid="#F5F5F5",high="#DD776E",limits=c(-2.5,2.5),name="Gene-wise\nZ-score")+labs(x="Trajectory state",y=NULL)+theme_classic(base_family="Arial",base_size=9)+theme(axis.text.x=element_text(face="bold"),axis.text.y=element_text(face="italic",size=7),axis.ticks=element_blank(),axis.title.x=element_text(face="bold"),strip.text.y=element_text(face="bold",size=9),strip.background=element_rect(fill="#F0F0F0",color=NA),panel.spacing.y=grid::unit(.8,"mm"),plot.margin=margin(4,5,4,4));save2(pt,"10_top25_ZTQ_S_and_G2M_genes_expression_heatmap",5.1,8.0)
writeLines(c("ZTQ G2 and M marker lists were merged by union and deduplicated before analysis.",paste0("G2 genes=",length(g2),", M genes=",length(m),", merged G2/M genes=",length(g2m),", G2-M overlap=",length(overlap_g2_m),"."),paste0("S genes=",length(s),", S-G2/M overlap=",length(overlap_s_g2m),"."),paste0("Detected genes: S=",sum(det$program=="S"),", G2/M=",sum(det$program=="G2/M"),"."),"RNA expression was log-normalized and averaged across subclusters 0 -> 2 -> 4 -> 1 -> 8.","Heatmaps show gene-wise Z-scores capped at +/-2.5. The module plot averages gene-wise Z-scores so every gene contributes equally.","Figures are PDF and PNG only."),file.path(outdir,"11_method_information.txt"));writeLines(capture.output(sessionInfo()),file.path(outdir,"12_sessionInfo.txt"));print(table(long$program,long$detected));print(curve)
