# Portable path configuration (override with environment variables).
project_dir <- Sys.getenv("SHOOT_REGEN_PROJECT_DIR", unset = ".")
output_root <- Sys.getenv("SHOOT_REGEN_OUTPUT_DIR", unset = file.path(project_dir, "02_results"))
external_data_dir <- Sys.getenv("SHOOT_REGEN_EXTERNAL_DATA_DIR", unset = file.path(project_dir, "external_data"))
work_dir <- Sys.getenv("SHOOT_REGEN_WORK_DIR", unset = ".")

suppressPackageStartupMessages({library(Seurat);library(monocle3);library(ggplot2);library(patchwork)})
input_rds<-file.path(project_dir, "01_obj/01_WT_snRNA/03_snRNA_C0-2-3-subclustered_res0.4_SIM4-SIM16.rds")
outdir<-Sys.getenv("MONOCLE_OUTDIR",file.path(output_root, "125_WT_res04_C02418_monocle3_trajectory"))
dir.create(outdir,recursive=TRUE,showWarnings=FALSE)
states<-c("0","2","4","1","8");dates<-c("SIM4","SIM6","SIM8","SIM10","SIM14","SIM16")
state_cols<-c("0"="#EBCC50","2"="#EB8950","4"="#EB505A","1"="#EBAB50","8"="#86431C")
date_cols<-c("SIM4"="#3C5488","SIM6"="#4DBBD5","SIM8"="#00A087","SIM10"="#91D1C2","SIM14"="#F39B7F","SIM16"="#E64B35")
obj<-readRDS(input_rds);obj<-subset(obj,subset=subcluster%in%states);obj$subcluster<-factor(as.character(obj$subcluster),levels=states);obj$date<-factor(as.character(obj$date),levels=dates);DefaultAssay(obj)<-"RNA"
counts<-GetAssayData(obj,assay="RNA",slot="counts");cell_md<-obj@meta.data;gene_md<-data.frame(gene_short_name=rownames(counts),row.names=rownames(counts))
cds<-new_cell_data_set(counts,cell_metadata=cell_md,gene_metadata=gene_md)
set.seed(128);cds<-preprocess_cds(cds,num_dim=30,method="PCA",norm_method="log",verbose=FALSE);cds<-reduce_dimension(cds,reduction_method="UMAP",umap.metric="cosine",umap.min_dist=.2,umap.n_neighbors=30,cores=1,verbose=FALSE);cds<-cluster_cells(cds,reduction_method="UMAP",k=30,verbose=FALSE)
partition_before<-as.data.frame(table(subcluster=colData(cds)$subcluster,partition=partitions(cds)));write.csv(partition_before,file.path(outdir,"02_monocle_partition_by_subcluster.csv"),row.names=FALSE)
# A single graph is learned across partitions to test the proposed continuum; interpretation remains branch-aware.
cds<-learn_graph(cds,use_partition=FALSE,close_loop=FALSE,learn_graph_control=list(minimal_branch_len=10),verbose=FALSE)
root_cells<-rownames(colData(cds))[as.character(colData(cds)$subcluster)=="0"&as.character(colData(cds)$date)=="SIM4"]
if(!length(root_cells))stop("No SIM4 cluster-0 root cells found")
closest_vertex<-as.matrix(cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex)
root_vertex_counts<-sort(table(closest_vertex[root_cells,1]),decreasing=TRUE)
root_pr_node<-igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names(root_vertex_counts)[1])]
writeLines(c(paste("root_principal_node",root_pr_node),paste("SIM4_cluster0_cells",length(root_cells)),paste("cells_nearest_root_node",root_vertex_counts[1])),file.path(outdir,"02b_root_node_information.txt"))
cds<-order_cells(cds,reduction_method="UMAP",root_pr_nodes=root_pr_node);pt<-pseudotime(cds)
celltab<-data.frame(cell=names(pt),subcluster=as.character(colData(cds)$subcluster),date=as.character(colData(cds)$date),pseudotime=as.numeric(pt));write.csv(celltab,file.path(outdir,"03_cell_pseudotime.csv"),row.names=FALSE)
summary_tab<-do.call(rbind,lapply(states,function(cl){x<-celltab$pseudotime[celltab$subcluster==cl&is.finite(celltab$pseudotime)];data.frame(subcluster=cl,n_cells=length(x),median_pseudotime=median(x),mean_pseudotime=mean(x),q25=as.numeric(quantile(x,.25)),q75=as.numeric(quantile(x,.75)),min=min(x),max=max(x))}));write.csv(summary_tab,file.path(outdir,"04_pseudotime_summary_by_subcluster.csv"),row.names=FALSE)
date_summary<-do.call(rbind,lapply(dates,function(dd){x<-celltab$pseudotime[celltab$date==dd&is.finite(celltab$pseudotime)];data.frame(date=dd,n_cells=length(x),median_pseudotime=if(length(x))median(x)else NA,mean_pseudotime=if(length(x))mean(x)else NA)}));write.csv(date_summary,file.path(outdir,"05_pseudotime_summary_by_date.csv"),row.names=FALSE)
base_args<-list(cds=cds,label_cell_groups=FALSE,label_leaves=FALSE,label_branch_points=FALSE,show_trajectory_graph=TRUE,cell_size=.28,graph_label_size=2)
p_state<-do.call(plot_cells,c(base_args,list(color_cells_by="subcluster")))+scale_color_manual(values=state_cols,breaks=states,drop=FALSE)+ggtitle("Cell state")
p_date<-do.call(plot_cells,c(base_args,list(color_cells_by="date")))+scale_color_manual(values=date_cols,breaks=dates,drop=FALSE)+ggtitle("Sampling time")
p_pt<-do.call(plot_cells,c(base_args,list(color_cells_by="pseudotime")))+ggtitle("Pseudotime")
comb<-p_state+p_date+p_pt+plot_layout(ncol=3,guides="collect")
ggsave(file.path(outdir,"06_C02418_trajectory_state_date_pseudotime.pdf"),comb,width=12.2,height=4.05,device=cairo_pdf);ggsave(file.path(outdir,"06_C02418_trajectory_state_date_pseudotime.svg"),comb,width=12.2,height=4.05,device=grDevices::svg);ggsave(file.path(outdir,"06_C02418_trajectory_state_date_pseudotime.png"),comb,width=12.2,height=4.05,dpi=450,bg="white")
finite<-celltab[is.finite(celltab$pseudotime),];finite$subcluster<-factor(finite$subcluster,levels=states);finite$date<-factor(finite$date,levels=dates)
th<-theme_classic(base_family="Arial",base_size=10)+theme(axis.text=element_text(size=9,colour="black"),axis.title=element_text(size=10,face="bold"),legend.position="none",plot.margin=margin(5,5,5,5))
p_v<-ggplot(finite,aes(subcluster,pseudotime,fill=subcluster))+geom_violin(scale="width",trim=TRUE,linewidth=.25)+geom_boxplot(width=.12,outlier.shape=NA,fill="white",linewidth=.3)+scale_fill_manual(values=state_cols)+labs(x="Subcluster",y="Pseudotime")+th
ggsave(file.path(outdir,"07_pseudotime_by_subcluster.pdf"),p_v,width=4.25,height=3.25,device=cairo_pdf);ggsave(file.path(outdir,"07_pseudotime_by_subcluster.svg"),p_v,width=4.25,height=3.25,device=grDevices::svg);ggsave(file.path(outdir,"07_pseudotime_by_subcluster.png"),p_v,width=4.25,height=3.25,dpi=500,bg="white")
p_d<-ggplot(finite,aes(date,pseudotime,fill=date))+geom_violin(scale="width",trim=TRUE,linewidth=.25)+geom_boxplot(width=.12,outlier.shape=NA,fill="white",linewidth=.3)+scale_fill_manual(values=date_cols)+labs(x=NULL,y="Pseudotime")+th+theme(axis.text.x=element_text(angle=35,hjust=1))
ggsave(file.path(outdir,"08_pseudotime_by_date.pdf"),p_d,width=4.8,height=3.25,device=cairo_pdf);ggsave(file.path(outdir,"08_pseudotime_by_date.svg"),p_d,width=4.8,height=3.25,device=grDevices::svg);ggsave(file.path(outdir,"08_pseudotime_by_date.png"),p_d,width=4.8,height=3.25,dpi=500,bg="white")
# Bin pseudotime and quantify cell-state composition along the learned graph.
finite$pt_bin<-cut(finite$pseudotime,breaks=quantile(finite$pseudotime,probs=seq(0,1,length.out=11),na.rm=TRUE),include.lowest=TRUE,labels=1:10,duplicates="drop");bt<-as.data.frame(table(pt_bin=finite$pt_bin,subcluster=finite$subcluster));bt$fraction<-ave(bt$Freq,bt$pt_bin,FUN=function(x)x/sum(x));write.csv(bt,file.path(outdir,"09_state_composition_across_pseudotime_bins.csv"),row.names=FALSE)
p_bin<-ggplot(bt,aes(pt_bin,fraction,fill=subcluster))+geom_col(width=.82,colour="white",linewidth=.2)+scale_fill_manual(values=state_cols,breaks=states,drop=FALSE,name="Subcluster")+scale_y_continuous(labels=scales::percent)+labs(x="Pseudotime bin",y="Cell-state composition")+theme_classic(base_family="Arial",base_size=10)+theme(legend.position="top")
ggsave(file.path(outdir,"10_state_composition_across_pseudotime.pdf"),p_bin,width=5.3,height=3.45,device=cairo_pdf);ggsave(file.path(outdir,"10_state_composition_across_pseudotime.svg"),p_bin,width=5.3,height=3.45,device=grDevices::svg);ggsave(file.path(outdir,"10_state_composition_across_pseudotime.png"),p_bin,width=5.3,height=3.45,dpi=500,bg="white")
saveRDS(cds,file.path(outdir,"11_C02418_monocle3_cds_with_pseudotime.rds"),compress=FALSE)
writeLines(c("Monocle 3 analysis of WT res.0.4 subclusters 0,2,4,1,8.","Cells were selected but not forced into the stated order. PCA and UMAP were recomputed from RNA counts; a principal graph was learned across partitions.",sprintf("Root principal node: %s, selected as the graph node containing the largest number of the %s D4 cluster-0 cells.",root_pr_node,format(length(root_cells),big.mark=",")),"Because use_partition=FALSE connects states into a common graph, graph topology and pseudotime support a trajectory hypothesis but do not by themselves prove lineage direction or obligatory transitions."),file.path(outdir,"12_method_and_interpretation_notes.txt"))
cat("Completed:",outdir,"\n")
